sudo: required

language: perl6

os:
  - linux
  - osx

perl6:
  - 2015.12
  - latest

install:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update                ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagickwand5 ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew update                            ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew install imagemagick               ; fi

script: prove -v -e perl6 t/
