sudo: required

language: perl6

os:
  - linux
  - osx

perl6:
    - 2015.12
    - latest

install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libmagickwand-dev

script: prove -v -e perl6 t/
