os: Visual Studio 2015

platform: x64

install:
  # Install ImageMagick v7 DLLs
  - SET MAGICK_DLL_INSTALLER=ImageMagick-7.0.8-14-Q16-x64-dll.exe
  - appveyor DownloadFile http://www.imagemagick.org/download/binaries/%MAGICK_DLL_INSTALLER%
  - "%MAGICK_DLL_INSTALLER% /SILENT"
  - SET MAGICK_DLL_INSTALLER=
  - SET PATH=C:\Program Files\ImageMagick-7.0.8-Q16;%PATH%
  # Install rakudostar for faster CI builds. No windows user will actually use
  # rakudobrew
  - choco install rakudostar
  # Refresh environment variables so zef works
  - refreshenv
  # And let us start testing...
  - cd %APPVEYOR_BUILD_FOLDER%

build: off

test_script:
  # Test for fun :)
  - zef install . --verbose

shallow_clone: true
